# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='job',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academicdegree',
            name='level',
            field=models.CharField(choices=[('1_bachelor', '1_bachelor'), ('2_master', '2_master'), ('3_doctor', '3_doctor')], max_length=50),
        ),
    ]
