# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20170515_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='seniority',
            field=models.CharField(choices=[('entry', 'entry'), ('mid', 'mid'), (('senior',), ('senior',)), ('executive', 'executive')], max_length=50),
        ),
    ]
